/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nfTdutchauctiontokenSol from "./NFTdutchauctiontoken.sol";
export type { nfTdutchauctiontokenSol };
export type { ERC20Token } from "./ERC20Token";
export type { NFTDutchAuction_ERC20Bids } from "./NFTDutchAuction_ERC20Bids";
